/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package victor_entidades;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.ClienteDAO;
import dao.EstacionamentoDAO;
import dao.PessoaDAO;
//import restaurante_2022.dao.PessoaDAO;
import Entidades.Cliente;
import Entidades.Estacionamento;
import Entidades.Pessoa;
import victor_entidades.DAOFactory;

/**
 *
 * @author Ana Leticia
 */
public class EstacionamentoJPanel extends javax.swing.JPanel {
    
    private EstacionamentoDAO dao = DAOFactory.createEstacionamentoDAO(); //criar ClienteDAO
    //private PessoaDAO daoP = DAOFactory.createDAO();

    /**
     * Creates new form ClienteJPanel
     */
    public EstacionamentoJPanel() {
        initComponents();
        atualizaTabela();
    }
    
    
    private void atualizaTabela(){
        List<Estacionamento> lista = dao.listar();
        DefaultTableModel dfm = (DefaultTableModel) jTableEstacionamento.getModel();
        int linhas = jTableEstacionamento.getRowCount();
        for(int i = 0; i < linhas; i++){
            dfm.removeRow(0);   
        }
        
        for (Estacionamento estacionamento : lista){
            Object[] linha = new Object[]{estacionamento.getCpf(), estacionamento.getNome(), estacionamento.getCod_vaga(), estacionamento.getPreco(), estacionamento.getHora_entrada(), estacionamento.getHora_saida()};
            dfm.addRow(linha);
            //JOptionPane.showMessageDialog(jButtonSalvar, linha);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        NomeLabel = new javax.swing.JLabel();
        CPFLabel = new javax.swing.JLabel();
        VagaLabel = new javax.swing.JLabel();
        NascLabel = new javax.swing.JLabel();
        FidelidadeLabel = new javax.swing.JLabel();
        CpfTextField = new javax.swing.JTextField();
        NomeTextField = new javax.swing.JTextField();
        CodVagaTextField = new javax.swing.JTextField();
        PrecoTextField = new javax.swing.JTextField();
        EntradaTextField = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstacionamento = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        SaidaTextField = new javax.swing.JTextField();
        FidelidadeLabel1 = new javax.swing.JLabel();

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Aniversário", "Endereço", "Fidelidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        setBorder(javax.swing.BorderFactory.createTitledBorder("Estacionamento"));

        NomeLabel.setText("Nome:");

        CPFLabel.setText("CPF:");

        VagaLabel.setText("Vaga:");

        NascLabel.setText("Preço");

        FidelidadeLabel.setText("Entrada (HH:MM)");

        CpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfTextFieldActionPerformed(evt);
            }
        });

        PrecoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecoTextFieldActionPerformed(evt);
            }
        });

        EntradaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTextFieldActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTableEstacionamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Vaga", "Preço", "Entrada", "Saída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEstacionamento);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        SaidaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaidaTextFieldActionPerformed(evt);
            }
        });

        FidelidadeLabel1.setText("Saída (HH:MM)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonExcluir))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CPFLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(NomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NomeTextField)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VagaLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CodVagaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NascLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PrecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FidelidadeLabel)
                            .addComponent(FidelidadeLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SaidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EntradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VagaLabel)
                    .addComponent(CodVagaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NascLabel)
                    .addComponent(PrecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FidelidadeLabel)
                    .addComponent(EntradaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FidelidadeLabel1)
                    .addComponent(SaidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButtonEditar)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpfTextFieldActionPerformed

    private void PrecoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecoTextFieldActionPerformed

    private void EntradaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTextFieldActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        CpfTextField.setText("");
        NomeTextField.setText("");
        CodVagaTextField.setText("");
        PrecoTextField.setText("");
        EntradaTextField.setText("");
        SaidaTextField.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        Estacionamento estacionamento = new Estacionamento();   
        try{
            //JOptionPane.showMessageDialog(jButtonSalvar, "try");
            String cpf = CpfTextField.getText();
            estacionamento.setCpf(cpf);
            estacionamento.setNome(NomeTextField.getText());
            estacionamento.setCod_vaga(Integer.parseInt(CodVagaTextField.getText()));
            estacionamento.setPreco(Float.parseFloat(PrecoTextField.getText()));
            estacionamento.setHora_entrada(EntradaTextField.getText());
            estacionamento.setHora_saida(SaidaTextField.getText());
            dao.editar(estacionamento);
        }catch(NumberFormatException e){
            //JOptionPane.showMessageDialog(jButtonSalvar, "catch");
            estacionamento.setCpf(CpfTextField.getText());
            estacionamento.setNome(NomeTextField.getText());
            estacionamento.setCod_vaga(Integer.parseInt(CodVagaTextField.getText()));
            estacionamento.setPreco(Float.parseFloat(PrecoTextField.getText()));
            estacionamento.setHora_entrada(EntradaTextField.getText());
            estacionamento.setHora_saida(SaidaTextField.getText());
            dao.adicionar(estacionamento);
        }
        JOptionPane.showMessageDialog(jButtonSalvar, "Salvo com sucesso!");
        atualizaTabela();
        CpfTextField.setEnabled(true);
        EntradaTextField.setEnabled(true);
        jButtonCancelarActionPerformed(evt);     
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if(jTableEstacionamento.getSelectedRowCount() == 1){
            int linha = jTableEstacionamento.getSelectedRow();
            CpfTextField.setEnabled(false);
            EntradaTextField.setEnabled(false);
            
            CpfTextField.setText(jTableEstacionamento.getValueAt(linha, 0)+"");
            NomeTextField.setText(jTableEstacionamento.getValueAt(linha, 1)+"");
            CodVagaTextField.setText(jTableEstacionamento.getValueAt(linha, 2)+"");
            PrecoTextField.setText(jTableEstacionamento.getValueAt(linha, 3)+"");
            EntradaTextField.setText(jTableEstacionamento.getValueAt(linha, 4)+"");
            SaidaTextField.setText(jTableEstacionamento.getValueAt(linha, 5)+"");
        }else{
            JOptionPane.showMessageDialog(jButtonSalvar, "Selecione apenas uma linha!");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (jTableEstacionamento.getSelectedRowCount() >= 1){
            int[] linhas = jTableEstacionamento.getSelectedRows();
            for (int i = linhas.length - 1; i >= 0; i--){
                String cpf = jTableEstacionamento.getValueAt(linhas[i], 0)+"";
                dao.remover(cpf);
            }
            JOptionPane.showMessageDialog(jButtonSalvar, "Removido com sucesso!");
            atualizaTabela();
        }else{
            JOptionPane.showMessageDialog(jButtonSalvar, "Selecione ao menos uma linha!");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void SaidaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaidaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaidaTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JTextField CodVagaTextField;
    private javax.swing.JTextField CpfTextField;
    private javax.swing.JTextField EntradaTextField;
    private javax.swing.JLabel FidelidadeLabel;
    private javax.swing.JLabel FidelidadeLabel1;
    private javax.swing.JLabel NascLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JTextField PrecoTextField;
    private javax.swing.JTextField SaidaTextField;
    private javax.swing.JLabel VagaLabel;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableEstacionamento;
    // End of variables declaration//GEN-END:variables
}
