/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package victor_entidades;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import dao.FuncionarioDAO;
import dao.PessoaDAO;
//import restaurante_2022.entidades.Cliente;
import Entidades.Funcionario;
import Entidades.Pessoa;
import victor_entidades.DAOFactory;

/**
 *
 * @author Ana Leticia
 */
public class FuncionarioJPanel extends javax.swing.JPanel {

    private FuncionarioDAO dao = DAOFactory.createFunDAO(); //criar ClienteDAO
    private PessoaDAO daoP = DAOFactory.createDAO();
    /**
     * Creates new form ClienteJPanel
     */
    public FuncionarioJPanel() {
        initComponents();
        atualizaTabela();
    }

     private String data(){
        String format = "";
        String[] data = NascTextField.getText().split("");
        for (int i = 0; i < 8; i++){
            if (i == 2 || i == 4){
                format += "/";
            }
            format += data[i];
        }    
        return format;
    }
     
     private void atualizaTabela(){
        List<Funcionario> lista = dao.listar();
        DefaultTableModel dfm = (DefaultTableModel) jTableFuncionarios.getModel();
        int linhas = jTableFuncionarios.getRowCount();
        for(int i = 0; i < linhas; i++){
            dfm.removeRow(0);   
        }
        
        for (Funcionario fun : lista){
            Object[] linha = new Object[]{fun.getFunc().getCpf(), fun.getFunc().getNome(), fun.getFunc().getTelefone(), fun.getFunc().getData_nasc(), fun.getSalario()};
            dfm.addRow(linha);
            //JOptionPane.showMessageDialog(jButtonSalvar, linha);
        }
    }
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        NomeLabel = new javax.swing.JLabel();
        CPFLabel = new javax.swing.JLabel();
        TelLabel = new javax.swing.JLabel();
        NascLabel = new javax.swing.JLabel();
        SalarioLabel = new javax.swing.JLabel();
        CpfTextField = new javax.swing.JTextField();
        NomeTextField = new javax.swing.JTextField();
        TelTextField = new javax.swing.JTextField();
        NascTextField = new javax.swing.JTextField();
        SalarioTextField = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Aniversário", "Endereço", "Fidelidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionários"));

        NomeLabel.setText("Nome:");

        CPFLabel.setText("CPF:");

        TelLabel.setText("Telefone:");

        NascLabel.setText("Data de Nascimento(DDMMYYYY):");

        SalarioLabel.setText("Salário");

        CpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CpfTextFieldActionPerformed(evt);
            }
        });

        NascTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NascTextFieldActionPerformed(evt);
            }
        });

        SalarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioTextFieldActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Aniversário", "Salario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFuncionarios);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NascLabel)
                            .addComponent(TelLabel)
                            .addComponent(SalarioLabel)
                            .addComponent(CPFLabel)
                            .addComponent(NomeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CpfTextField)
                                    .addComponent(TelTextField)
                                    .addComponent(NascTextField)
                                    .addComponent(SalarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 387, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonEditar)
                                .addComponent(jButtonExcluir))
                            .addComponent(jButtonCancelar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(0, 500, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFLabel)
                    .addComponent(CpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeLabel)
                    .addComponent(NomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelLabel)
                    .addComponent(TelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NascLabel)
                    .addComponent(NascTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SalarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SalarioLabel))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSalvar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jButtonEditar)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CpfTextFieldActionPerformed

    private void NascTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NascTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NascTextFieldActionPerformed

    private void SalarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioTextFieldActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        CpfTextField.setText("");
        NomeTextField.setText("");
        TelTextField.setText("");
        NascTextField.setText("");
        SalarioTextField.setText("");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        Pessoa pessoa = new Pessoa();   
        Funcionario fun = new Funcionario();
        try{
            //JOptionPane.showMessageDialog(jButtonSalvar, "try");
            int nasc = NascTextField.getText().length();
            if (nasc < 9){
                pessoa.setCpf(CpfTextField.getText());
                pessoa.setNome(NomeTextField.getText());
                pessoa.setTelefone(TelTextField.getText());
                pessoa.setData_nasc(data());
                fun.setFunc(pessoa);
                fun.setSalario(Float.parseFloat(SalarioTextField.getText()));
                dao.adicionar(fun);
            }else{
                pessoa.setCpf(CpfTextField.getText());
                pessoa.setNome(NomeTextField.getText());
                pessoa.setTelefone(TelTextField.getText());
                pessoa.setData_nasc(NascTextField.getText());
                fun.setFunc(pessoa);
                fun.setSalario(Float.parseFloat(SalarioTextField.getText()));
                dao.editar(fun);
            }
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(jButtonSalvar, "Preencha os dados corretamente!");
        }
        JOptionPane.showMessageDialog(jButtonSalvar, "Salvo com sucesso!");
        atualizaTabela();
        CpfTextField.setEnabled(true);
        NascTextField.setEnabled(true);
        jButtonCancelarActionPerformed(evt);    
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if(jTableFuncionarios.getSelectedRowCount() == 1){
            int linha = jTableFuncionarios.getSelectedRow();
            CpfTextField.setEnabled(false);
            NascTextField.setEnabled(false);
            
            CpfTextField.setText(jTableFuncionarios.getValueAt(linha, 0)+"");
            NomeTextField.setText(jTableFuncionarios.getValueAt(linha, 1)+"");
            TelTextField.setText(jTableFuncionarios.getValueAt(linha, 2)+"");
            NascTextField.setText(jTableFuncionarios.getValueAt(linha, 3)+"");
            SalarioTextField.setText(jTableFuncionarios.getValueAt(linha, 4)+"");    
        }else{
            JOptionPane.showMessageDialog(jButtonSalvar, "Selecione apenas uma linha!");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        if (jTableFuncionarios.getSelectedRowCount() >= 1){
            int[] linhas = jTableFuncionarios.getSelectedRows();
            for (int i = linhas.length - 1; i >= 0; i--){
                String cpf = jTableFuncionarios.getValueAt(linhas[i], 0)+"";
                dao.remover(cpf);
            }
            JOptionPane.showMessageDialog(jButtonSalvar, "Removido com sucesso!");
            atualizaTabela();
        }else{
            JOptionPane.showMessageDialog(jButtonSalvar, "Selecione ao menos uma linha!");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFLabel;
    private javax.swing.JTextField CpfTextField;
    private javax.swing.JLabel NascLabel;
    private javax.swing.JTextField NascTextField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField NomeTextField;
    private javax.swing.JLabel SalarioLabel;
    private javax.swing.JTextField SalarioTextField;
    private javax.swing.JLabel TelLabel;
    private javax.swing.JTextField TelTextField;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTable jTableFuncionarios;
    // End of variables declaration//GEN-END:variables
}
