/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package victor_entidades;

/**
 *
 * @author Ana Leticia
 */
public class PRestauranteJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PRestauranteJFrame
     */
    public PRestauranteJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelConteudo = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuRestaurante = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFuncionarios = new javax.swing.JMenuItem();
        jMenuItemVendas = new javax.swing.JMenuItem();
        jMenuItemEstacionamento = new javax.swing.JMenuItem();
        jMenuItemRestaurante = new javax.swing.JMenuItem();
        jMenuItemReserva = new javax.swing.JMenuItem();
        jMenuItemEndereco = new javax.swing.JMenuItem();
        jMenuItemFornecedora = new javax.swing.JMenuItem();
        jMenuItemFinanceiro = new javax.swing.JMenuItem();
        jMenuItemBebida = new javax.swing.JMenuItem();
        jMenuItemCardapio = new javax.swing.JMenuItem();
        jMenuItemClassificacao = new javax.swing.JMenuItem();
        jMenuItemComanda = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemEstoque = new javax.swing.JMenuItem();
        jMenuItemFidelidade = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelConteudo.setLayout(new javax.swing.BoxLayout(jPanelConteudo, javax.swing.BoxLayout.LINE_AXIS));

        jMenuRestaurante.setText("Restaurante");
        jMenuRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRestauranteActionPerformed(evt);
            }
        });

        jMenuItemCliente.setText("Clientes");
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemCliente);

        jMenuItemFuncionarios.setText("Funcionarios");
        jMenuItemFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionariosActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemFuncionarios);

        jMenuItemVendas.setText("Vendas");
        jMenuItemVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVendasActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemVendas);

        jMenuItemEstacionamento.setText("Estacionamento");
        jMenuItemEstacionamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstacionamentoActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemEstacionamento);

        jMenuItemRestaurante.setText("Restaurante");
        jMenuItemRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRestauranteActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemRestaurante);

        jMenuItemReserva.setText("Reserva");
        jMenuItemReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservaActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemReserva);

        jMenuItemEndereco.setText("Endereço");
        jMenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnderecoActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemEndereco);

        jMenuItemFornecedora.setText("Fornecedora");
        jMenuItemFornecedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoraActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemFornecedora);

        jMenuItemFinanceiro.setText("Financeiro");
        jMenuItemFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinanceiroActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemFinanceiro);

        jMenuItemBebida.setText("Bebida");
        jMenuItemBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBebidaActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemBebida);

        jMenuItemCardapio.setText("Cardapio");
        jMenuItemCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCardapioActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemCardapio);

        jMenuItemClassificacao.setText("Classificação");
        jMenuItemClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClassificacaoActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemClassificacao);

        jMenuItemComanda.setText("Comanda");
        jMenuItemComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComandaActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemComanda);

        jMenuItem2.setText("Entrega");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItem2);

        jMenuItemEstoque.setText("Estoque");
        jMenuItemEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstoqueActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemEstoque);

        jMenuItemFidelidade.setText("Fidelidade");
        jMenuItemFidelidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFidelidadeActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemFidelidade);

        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuRestaurante.add(jMenuItemProduto);

        jMenuBar.add(jMenuRestaurante);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new ClienteJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRestauranteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuRestauranteActionPerformed

    private void jMenuItemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionariosActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new FuncionarioJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionariosActionPerformed

    private void jMenuItemVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVendasActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new VendasJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemVendasActionPerformed

    private void jMenuItemEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstacionamentoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new EstacionamentoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstacionamentoActionPerformed

    private void jMenuItemRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRestauranteActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new RestauranteJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemRestauranteActionPerformed

    private void jMenuItemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservaActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new ReservaJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemReservaActionPerformed

    private void jMenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnderecoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new EnderecoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemEnderecoActionPerformed

    private void jMenuItemFornecedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoraActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new FornecedoraJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedoraActionPerformed

    private void jMenuItemFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinanceiroActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new FinanceiroJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemFinanceiroActionPerformed

    private void jMenuItemBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBebidaActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new BebidaJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemBebidaActionPerformed

    private void jMenuItemCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCardapioActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new CardapioJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemCardapioActionPerformed

    private void jMenuItemClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClassificacaoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new ClassificacaoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemClassificacaoActionPerformed

    private void jMenuItemComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComandaActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new ComandaJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemComandaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new EntregaJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstoqueActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new EstoqueJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemEstoqueActionPerformed

    private void jMenuItemFidelidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFidelidadeActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new FidelidadeJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemFidelidadeActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new ProdutoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRestauranteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRestauranteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRestauranteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRestauranteJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRestauranteJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemBebida;
    private javax.swing.JMenuItem jMenuItemCardapio;
    private javax.swing.JMenuItem jMenuItemClassificacao;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemComanda;
    private javax.swing.JMenuItem jMenuItemEndereco;
    private javax.swing.JMenuItem jMenuItemEstacionamento;
    private javax.swing.JMenuItem jMenuItemEstoque;
    private javax.swing.JMenuItem jMenuItemFidelidade;
    private javax.swing.JMenuItem jMenuItemFinanceiro;
    private javax.swing.JMenuItem jMenuItemFornecedora;
    private javax.swing.JMenuItem jMenuItemFuncionarios;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemReserva;
    private javax.swing.JMenuItem jMenuItemRestaurante;
    private javax.swing.JMenuItem jMenuItemVendas;
    private javax.swing.JMenu jMenuRestaurante;
    private javax.swing.JPanel jPanelConteudo;
    // End of variables declaration//GEN-END:variables
}
